# TIN - Porównanie wybranych implementacji protokołów TCP i QUIC
# Utworzono: 29.05.2021
# Autor: Piotr Sawicki

name: Tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: psawicki0/tin:latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j$(nproc)

    - name: Start servers
      run: tests/start_servers.sh ${{github.workspace}}
      working-directory: ${{github.workspace}}

    - name: Test
      run: cd ${{github.workspace}}/build && ctest --extra-verbose --build-config ${{env.BUILD_TYPE}} --exclude-regex logger_test